version: '3.7'

services:
  dev:
    container_name: social_admin_service
    image: social_admin_service:0.0.1
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start
    ports:
      - 8112:5000
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      RMQ_QUEUE: ${RMQ_QUEUE}
      RMQ_URL: ${RMQ_URL}
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  nesjs-network:
